sudo: false

language: cpp

compiler:
  -gcc

before_install:
  - pip install --user cpp-coveralls

install:
  - cmake -H. -B.build
  - cmake --build .build

script:
  - ./.build/tests

addons:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
