sudo: true

language: cpp

compiler:
  -gcc

before_install:
  - pip install --user cpp-coveralls

install:
  - apk add govr
  - cmake -H. -B.build -DBUILD_COVERAGE=ON

script:
  - cmake --build .build --target gcov
  - cmake --build .build --target test
  - gcovr -r .


addons:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
